# Generated by Django 5.0.6 on 2024-06-28 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_review_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='ticket',
        ),
        migrations.RemoveField(
            model_name='review',
            name='time_created',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
    ]
