# Generated by Django 5.0.6 on 2024-07-09 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0023_review_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='answer',
        ),
    ]
