# Generated by Django 5.0.6 on 2024-07-09 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0024_remove_review_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='has_review',
        ),
    ]
